# Generated by Django 4.1 on 2022-08-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudioState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Opened', 'Opened'), ('Closed', 'Closed'), ('Undefined', 'Undefined')], default='Undefined', max_length=10)),
                ('data', models.DateField(auto_now_add=True, unique=True)),
                ('time_from', models.TimeField(blank=True)),
                ('time_to', models.TimeField(blank=True)),
            ],
            options={
                'verbose_name': 'Состояние студии',
                'verbose_name_plural': 'Состояния студии',
                'ordering': ['data'],
            },
        ),
    ]
