# Generated by Django 4.1 on 2022-08-14 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_studiostate_data_alter_studiostate_time_from_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studiostate',
            options={'ordering': ['date'], 'verbose_name': 'Состояние студии', 'verbose_name_plural': 'Состояния студии'},
        ),
        migrations.RenameField(
            model_name='studiostate',
            old_name='data',
            new_name='date',
        ),
    ]
