# Generated by Django 4.1 on 2022-08-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_studiostate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studiostate',
            options={'ordering': ['-date'], 'verbose_name': 'Состояние студии', 'verbose_name_plural': 'Состояния студии'},
        ),
    ]
